### ISSUE TITLE
Create an API endpoint that lists loaded slices and extensions

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#1184]
Create an endpoint on the server that lists all the loaded extensions and slices. This endpoint should also included the version numbers.

**Comment by bartv** [comment]
Design of API endpoint that provides status information on the server. This endpoint provides status information on the orchestration server, including versions, loaded extensions (and their versions).

Each slice gets a get_status method that can report its internal status and it is collected by the 
api endpoint.

The structure of the API response is:
```
edition: community|service orchestrator
version: 2019.3.5
license: APL2|Inmanta EULA
extensions:
    - name: lsm
      version: 2019.3
slices: 
    - name: core.database
      status: 
        connected: true
        servers: [localhost]
    - name: core.restserver
      status:
        listenon: 8888
    - name: core.agentmanager
      status:
        connected_agents: 45
    - name: lcm.database
      status:
        connected: true
        servers: [localhost]
```
